name: Python CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-bundle
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ vars.REGION }}
          role-to-assume: ${{ vars.OIDC_ROLE }}
          role-session-name: IAM-Github-Actions-TF
      
      - name: Deploy to AWS
        run: |
          aws lambda update-function-code --function-name ${{ vars.LAMBDA_FUNCTION_NAME }} --zip-file fileb://lambda_function.zip